/*
 Developers : Mike Duffenais and Chad Paquet
 Since: Feb 10 2014


 *items.Java
 */
package fposs;

import fposs.database.DbUtil;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mike Duffenais and Chad Paquet
 */
public class Items extends javax.swing.JFrame {

    /**
     * Creates new form Items
     */
// Declare Vars 
    String categories[][];
    int selected;
    String[][] itemsLoad;

    // constructor 
    public Items() throws SQLException {
        initComponents();
        onCreate();
    }
// onCreate function 

    public void onCreate() throws SQLException {
        // set default close operation 

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        // get array of items to load 
        itemsLoad = DbUtil.loadItems();
// get array of categories 
        categories = DbUtil.loadCategories();
        ArrayList catList = new ArrayList();
        // populate combo box 
        for (String[] categorie : categories) {
            jComboBox1.addItem(categorie[1]);
        }
        // add items to list1
        for (int i = 0; i < itemsLoad.length; i++) {
            list1.add(itemsLoad[i][1]);
        }
        // set button visibility 
        buttonSaveAdd.setVisible(false);
        buttonSaveEdit.setVisible(false);
        buttonSaveDelete.setVisible(false);
        Cancel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        jComboBox1 = new javax.swing.JComboBox();
        textField3 = new java.awt.TextField();
        jComboBox2 = new javax.swing.JComboBox();
        textField4 = new java.awt.TextField();
        buttonSaveEdit = new javax.swing.JButton();
        buttonSaveAdd = new javax.swing.JButton();
        buttonSaveDelete = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Barcode");

        jLabel2.setText("Name");

        jLabel3.setText("Category");

        jLabel4.setText("Price");

        jLabel5.setText("Taxable");

        jLabel6.setText("Display Order");

        textField1.setEditable(false);
        textField1.setEnabled(false);
        textField1.setText("textField1");

        textField2.setEditable(false);
        textField2.setEnabled(false);
        textField2.setText("textField2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        jComboBox1.setEnabled(false);

        textField3.setEditable(false);
        textField3.setEnabled(false);
        textField3.setText("textField3");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));
        jComboBox2.setEnabled(false);

        textField4.setEditable(false);
        textField4.setEnabled(false);
        textField4.setText("textField4");

        buttonSaveEdit.setText("Save");
        buttonSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveEditActionPerformed(evt);
            }
        });

        buttonSaveAdd.setText("Save");
        buttonSaveAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveAddActionPerformed(evt);
            }
        });

        buttonSaveDelete.setText("Save");
        buttonSaveDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveDeleteActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSaveEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(buttonSaveDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(buttonSaveAdd))
                        .addGap(48, 48, 48)
                        .addComponent(Cancel)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSaveEdit)
                            .addComponent(buttonSaveAdd)
                            .addComponent(buttonSaveDelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Cancel)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        // get selected items and populate text fields 
        selected = list1.getSelectedIndex();
        textField1.setText(itemsLoad[selected][0]);
        textField2.setText(itemsLoad[selected][1]);
        jComboBox1.setSelectedIndex(Integer.parseInt(categories[Integer.parseInt(itemsLoad[selected][2]) - 1][0]) - 1);
        System.out.println(categories[Integer.parseInt(itemsLoad[selected][2]) - 1][0]);
        textField3.setText(itemsLoad[selected][3]);
        jComboBox2.setSelectedIndex(Integer.parseInt(itemsLoad[selected][4]));
        textField4.setText(itemsLoad[selected][5]);

    }//GEN-LAST:event_list1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//EDIT button action to hide and set visibility of fields and buttons 
        textField2.setEditable(true);
        textField2.setEnabled(true);
        textField3.setEditable(true);
        textField3.setEnabled(true);
        textField4.setEditable(true);
        textField4.setEnabled(true);
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        list1.setEnabled(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        buttonSaveEdit.setVisible(true);
        Cancel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveEditActionPerformed
// Edit save button sets fields visibility and saves updated info to database 
        textField2.setEditable(false);
        textField2.setEnabled(false);
        textField3.setEditable(false);
        textField3.setEnabled(false);
        textField4.setEditable(false);
        textField4.setEnabled(false);
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
        list1.setEnabled(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        try {
            // run function to save to DB 
            DbUtil.editItems(textField1.getText(), textField2.getText(),
                    Integer.parseInt(categories[jComboBox1.getSelectedIndex()][0]),
                    Double.parseDouble(textField3.getText()),
                    jComboBox2.getSelectedIndex(), Integer.parseInt(textField4.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
        }
        // remove all items from list and combo box 
        list1.removeAll();
        jComboBox1.removeAllItems();
        try {
            onCreate();
        } catch (SQLException ex) {
            Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonSaveEditActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//Delete  - set field visibility and button visibility 
        textField2.setEditable(true);
        textField2.setEnabled(true);
        textField3.setEditable(true);
        textField3.setEnabled(true);
        textField4.setEditable(true);
        textField4.setEnabled(true);
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        list1.setEnabled(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        Cancel.setVisible(true);
buttonSaveDelete.setVisible(true);    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonSaveDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveDeleteActionPerformed
// Button Save function Sets visibility and runs function to delete items 
        textField2.setEditable(false);
        textField2.setEnabled(false);
        textField3.setEditable(false);
        textField3.setEnabled(false);
        textField4.setEditable(false);
        textField4.setEnabled(false);
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
        list1.setEnabled(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        list1.removeAll();
        jComboBox1.removeAllItems();
        try {
            DbUtil.deleteItem(textField1.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            onCreate();
        } catch (SQLException ex) {
            Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonSaveDeleteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//SAVE  sets fields visibility and button visibility 
        textField1.setEditable(true);
        textField1.setEnabled(true);
        textField2.setEditable(true);
        textField2.setEnabled(true);
        textField3.setEditable(true);
        textField3.setEnabled(true);
        textField4.setEditable(true);
        textField4.setEnabled(true);
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(true);
        textField1.setText("");
        textField2.setText("");
        textField3.setText("");
        textField4.setText("");
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(-1);
        list1.setEnabled(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        Cancel.setVisible(true);
        buttonSaveAdd.setVisible(true);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void buttonSaveAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveAddActionPerformed
//ADD set vidibility  - and run function to add items to database
        textField1.setEditable(false);
        textField1.setEnabled(false);
        textField2.setEditable(false);
        textField2.setEnabled(false);
        textField3.setEditable(false);
        textField3.setEnabled(false);
        textField4.setEditable(false);
        textField4.setEnabled(false);
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
        list1.setEnabled(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        buttonSaveAdd.setVisible(false);
        try {
            // run function to add to DB 
            DbUtil.addItem(textField1.getText(), textField2.getText(), Integer.parseInt(categories[jComboBox1.getSelectedIndex()][0]),
                    Double.parseDouble(textField3.getText()), jComboBox2.getSelectedIndex(), Integer.parseInt(textField4.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox1.removeAllItems();
        list1.removeAll();

        try {
            onCreate();
        } catch (SQLException ex) {
            Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_buttonSaveAddActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
//Cancel button - Resets window 
        textField1.setEditable(false);
        textField1.setEnabled(false);
        textField1.setText("");
        textField2.setEditable(false);
        textField2.setEnabled(false);
        textField2.setText("");
        textField3.setEditable(false);
        textField3.setEnabled(false);
        textField3.setText("");
        textField4.setEditable(false);
        textField4.setEnabled(false);
        textField4.setText("");
        jComboBox1.setEnabled(false);
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setEnabled(false);
        jComboBox2.setSelectedIndex(-1);
        list1.setEnabled(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);


    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Items().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Items.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton buttonSaveAdd;
    private javax.swing.JButton buttonSaveDelete;
    private javax.swing.JButton buttonSaveEdit;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.List list1;
    private javax.swing.JMenuBar menuBar;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    // End of variables declaration//GEN-END:variables

}
